### ISSUE TITLE
Some named arguments still get a space before the colon

### ISSUE THREAD

**Issue by zEh-** [Leopotam/vscode-csharpfixformat#76] opened 2018-05-20 09:28 UTC
### C# FixFormat extension version:
0.0.70

### VsCode version:
1.23.1

## Steps to reproduce
Reformat:
```
public class ItemDefinition
{
    public static readonly ItemDefinition RocketLauncher = new ItemDefinition(
        type: ItemType.Weapon,
        className: "RocketLauncher",
        maxCount: 1
    );
}
```

## Expected  behavior
No change.

## Actual behavior
Formatted to:
```
public class ItemDefinition
{
    public static readonly ItemDefinition RocketLauncher = new ItemDefinition(
        type[!!! SPACE !!!]: ItemType.Weapon,
        className: "RocketLauncher",
        maxCount[!!! SPACE !!!]: 1
    );
}
```

**Comment by Leopotam** [comment] 2018-05-20 12:44
@zEh- issue partially fixed, but there is one "by design" behaviour - extension is not valid C# specs parser, but regular expression fixer without context dependent behaviour. Its why string constants between `" "` double quotes cant be used as values, this case will be added as corner case to README at new version:

### Named parameters with string consts as values can be formatted wrong:
*Expected:*
```
var test = Test(
    name: "Test name",
    amount: 1,
    type: TestType.Type1
    );
```
*Actual:*
```
var test = Test(
    name : "Test name",
    amount : 1,
    type : TestType.Type1
    );
```
*Suggestion* - extract string values as consts:
```
const string TestName = "Test name";
var test = Test(
    name: TestName,
    amount: 1,
    type: TestType.Type1
    );
```

 Can you check last state of develop branch? Is issue fixed for you?

**Comment by Leopotam** [comment] 2018-05-21 15:10
@zEh- no feedback, closed as fixed. 0.0.71 version released on marketplace.

**Closed by Leopotam** 2018-05-21 15:10 UTC
Labels: bug
