### ISSUE TITLE
Problems when try to format Enum

### ISSUE THREAD

**Issue by bernardbr** [Leopotam/vscode-csharpfixformat#30] opened 2017-11-10 14:07 UTC
### VsCode version:
Version 1.18.0
Commit dcee2202709a4f223185514b9275aa4229841aa7
Date 2017-11-08T21:22:49.932Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

## Steps to reproduce
Try to format this enum:

```csharp
    public enum EType
    {
        /// <summary>
        /// Test
        /// </summary>
        Value1 = 100,

        /// <summary>
        /// Test 2
        /// </summary>
        Value2 = 50,


        /// <summary>
        /// Test 3
        /// </summary>
        Value3 = 1500
    }
```
## Expected  behavior
The format works correct!

## Actual behavior
It will be formated as:
```csharp
    public enum EType
    {
        /// <summary>
        /// Test
        /// </summary>
        Value1 = 100,

            /// <summary>
            /// Test 2
            /// </summary>
            Value2 = 50,

            /// <summary>
            /// Test 3
            /// </summary>
            Value3 = 1500
    }
```

**Comment by Leopotam** [comment] 2017-11-10 14:16
@bernardbr cant reproduce, on empty c# file with your code it works as must. As nested enum type to class - works too. Looks like there is side effect of something else.

**Comment by bernardbr** [comment] 2017-11-10 20:43
@Leopotam maybe it sounds crazy, but only on my project, the problem occurs...

Could you try to reproduce in my project? https://github.com/Alterdata/NCalc-NetCore.git

In this case, please, open "EvaluationOption.cs" file, and press ```Shift``` + ```Alt``` + ```F```

Thanks!

**Comment by Leopotam** [comment] 2017-11-10 22:34
@bernardbr [it works on my side](https://youtu.be/U_xxMuYlDWw). Maybe problem in settings? I added only one tweak (without any others) to follow your codestyle:
> "csharpfixformat.style.braces.onSameLine": false

**Comment by bernardbr** [comment] 2017-11-11 14:15
This is my settings:
```json
{
    "csharpfixformat.sort.usings.splitGroups": true,
    "csharpfixformat.style.braces.onSameLine": false,
    "csharpfixformat.style.spaces.beforeParenthesis": false,
    "csharpfixformat.style.spaces.afterParenthesis": true,
    "csharpfixformat.style.spaces.beforeIndexerBracket": false,
    "csharpfixformat.style.spaces.beforeBracket": false,
    "csharpfixformat.style.spaces.afterBracket": false,
    "csharpfixformat.style.spaces.insideEmptyParenthis": false,
    "csharpfixformat.style.spaces.insideEmptyBraces": false,
    "csharpfixformat.style.spaces.insideEmptyBrackets": false
}
```

**Comment by Leopotam** [comment] 2017-11-11 15:51
@bernardbr looks like i found problem - your file indented with tabs instead of spaces. If its wrong, you can fix it with disabling autodetect indent character by vscode and force set to use spaces or tabs:

> "editor.detectIndentation": false,
> "editor.insertSpaces": true,

For tabs issue should be fixed too, can you check last develop branch on your side?

**Comment by bernardbr** [comment] 2017-11-11 17:04
Thanks @Leopotam 
Sorry I haven't seen it!

**Comment by bernardbr** [comment] 2017-11-11 17:04
Thanks @Leopotam
Sorry I haven't seen it!

**Comment by Leopotam** [comment] 2017-11-11 17:07
@bernardbr update in develop branch fixed this issue?

**Comment by bernardbr** [comment] 2017-11-12 01:58
It worked fine with develop branch!
Thank you very much!

**Comment by Leopotam** [comment] 2017-11-12 09:42
@bernardbr 0.0.40 released on official marketplace, you can uninstall custom package and install public release. thanks.

**Closed by Leopotam** 2017-11-12 09:42 UTC
Labels: bug
