### ISSUE TITLE
Deep settings of parenthesis

### ISSUE THREAD

**Issue by JSBmanD** [Leopotam/vscode-csharpfixformat#37] opened 2017-11-29 14:52 UTC
Hello, I need setting for parenthesis to place space before it in statements' constructions (if ()). And I don't need spaces in the other places. Is it possible?

**Comment by Leopotam** [comment] 2017-11-29 18:52
Edit, please, issue with predefined template, because now not clear what you want.

**Comment by JSBmanD** [comment] 2017-11-30 13:55
## Environment data
### C# FixFormat extension version:
Last

### VsCode version:
Last

## Steps to reproduce
- Set setting "csharpfixformat.style.spaces.beforeParenthesis": false

## Expected  behavior
One more setting like "csharpfixformat.style.spaces.beforeParenthesisInStatements": true
will place space after statement (if ()
{})

## Actual behavior
All spaces before parenthesis will be removed

**Comment by Leopotam** [comment] 2017-11-30 14:26
@JSBmanD Well, any method call is expression too, but you dont want to see spaces in this case, right? Looks like you want to add special case for space after c# keywords only?

**Comment by JSBmanD** [comment] 2017-11-30 14:36
@Leopotam yes, exactly.

**Comment by Leopotam** [comment] 2017-11-30 21:53
@JSBmanD so, can you provide keywords list that should be splitted from parenthesis?

**Comment by Leopotam** [comment] 2017-12-03 17:35
Closed, will be reopened after info will be provided.

**Comment by JSBmanD** [comment] 2017-12-14 15:55
If, switch, for, while.
P.S. Sorry, didn't notice you message.

**Comment by Leopotam** [comment] 2017-12-14 17:31
> Now "Format Selection" doesn't work.
[never worked #20.](#20)

**Comment by Leopotam** [comment] 2017-12-14 19:01
@JSBmanD cant reproduce your issue - even with "csharpfixformat.style.spaces.beforeParenthesis": false - for / if / switch works as you want - with spaces. can you provide c# code with reproducible issue?

**Comment by JSBmanD** [comment] 2017-12-14 19:05
It's not an issue, it's a suggestion of feature. I need separate settings for if, switch, for, while alongside with setting  "csharpfixformat.style.spaces.beforeParenthesis".

**Comment by Leopotam** [comment] 2017-12-14 19:20
@JSBmanD i mean, if / switch / for operators ignores this setting - space will be inserted in all cases.

**Comment by JSBmanD** [comment] 2017-12-14 19:45
@Leopotam oh, I don't know why I thought another way. How about setting for keeping case on 1 line when 1 line of code needed? Like:
`switch (sth)
		{
			case sth1: do(); break;
			case sth2: do1(); break;`

**Closed** 2017-12-14 19:45 UTC
Labels: enhancement, need more info

**Comment by Leopotam** [comment] 2017-12-14 20:12
@JSBmanD bad idea because alot of code cases can be written in one line. btw, for each programmer length of this line can be different. :)
